//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOFacade
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hastane
    {
        public Hastane()
        {
            this.Brans = new HashSet<Brans>();
            this.Doktor = new HashSet<Doktor>();
            this.Randevu = new HashSet<Randevu>();
        }
    
        public int ID { get; set; }
        public string Ad { get; set; }
    
        public virtual ICollection<Brans> Brans { get; set; }
        public virtual ICollection<Doktor> Doktor { get; set; }
        public virtual ICollection<Randevu> Randevu { get; set; }
    }
}
